# This is a basic workflow to help you get started with Actions

name: Gitee repos mirror periodic job

on:
  pull_request:
    paths:
    - '.github/workflows/**'
    # Runs at every pull requests submitted in master branch 
    branches: [ master ]
  push:
  schedule:
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@v1.0
      with:
        src: github/mgithubTestOrg
        dst: gitee/mgithubTestOrg
        dst_key: hub_mirror
        dst_token:  personal_token
        account_type: org
        timeout: 600
        debug: true
        force_update: true
        # black_list: "mysql-server,kunpeng-mpam,hadoop,kunpengcompute.github.io"
